version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: lmsBackend
    restart: always
    expose:
    - "5436"
    ports:
      - '5436:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: "lms"